In [4]:
import numpy as np


In [3]:
array=np.array([1,2,3,4])
array

array([1, 2, 3, 4])

In [7]:
array2=np.array([[1,2,3,4],[2,3,4,6]])
array2


array([[1, 2, 3, 4],
       [2, 3, 4, 6]])

In [9]:
array2.shape
array2.size

8

In [11]:
a= np.ones(3)
a

array([1., 1., 1.])

In [16]:
a= np.zeros(3)
a= np.zeros((1,3)) 
a= np.zeros((1,3),dtype='int') 
a

array([[0, 0, 0]])

In [5]:
l= np.arange(1,11)
l

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
random_array= np.random.random(10)
random_array

array([0.91379697, 0.10155136, 0.19390254, 0.86926884, 0.81986172,
       0.62233106, 0.80892791, 0.30028251, 0.53151414, 0.35264473])

In [7]:
random_array= np.random.randint(0,30,size=(10,5))
random_array

array([[21, 16, 25, 27, 12],
       [ 6, 18, 22,  7, 26],
       [19, 17,  6,  0, 16],
       [28, 27,  2, 10,  2],
       [ 5,  9, 10, 29,  3],
       [ 1, 24,  2,  6, 28],
       [ 0, 17,  5, 11, 28],
       [ 2, 13, 13,  6,  4],
       [28,  8, 15, 23, 17],
       [24,  1, 21,  5,  3]], dtype=int32)

In [8]:
random_array= np.random.randn(10)
random_array

array([-1.26763186,  0.81429936,  0.43411345,  0.34694886, -0.97360135,
       -0.19832617, -1.30985545, -2.13769952,  0.70255938,  0.56545579])

In [20]:
np.random.seed()
random_array= np.random.random((10,5))
random_array


array([[0.35742078, 0.65700845, 0.08527771, 0.41443501, 0.02338486],
       [0.69996254, 0.49151721, 0.66867206, 0.40687352, 0.7464322 ],
       [0.89019341, 0.21820456, 0.15519404, 0.91545887, 0.78391447],
       [0.37748709, 0.07665409, 0.34281358, 0.03274392, 0.130608  ],
       [0.52902569, 0.4848878 , 0.89080484, 0.38391987, 0.76846112],
       [0.36807815, 0.67614226, 0.55100374, 0.58235445, 0.61178393],
       [0.40082381, 0.29630524, 0.64223473, 0.11516998, 0.3992014 ],
       [0.62173395, 0.87748227, 0.3220825 , 0.91988782, 0.50285946],
       [0.78921001, 0.29978171, 0.0962227 , 0.21785991, 0.67765802],
       [0.89363284, 0.07927615, 0.23267669, 0.20857873, 0.12589896]])