In [5]:
import numpy as np


In [3]:
array=np.array([1,2,3,4])
array

array([1, 2, 3, 4])

In [7]:
array2=np.array([[1,2,3,4],[2,3,4,6]])
array2


array([[1, 2, 3, 4],
       [2, 3, 4, 6]])

In [9]:
array2.shape
array2.size

8

In [11]:
a= np.ones(3)
a

array([1., 1., 1.])

In [16]:
a= np.zeros(3)
a= np.zeros((1,3)) 
a= np.zeros((1,3),dtype='int') 
a

array([[0, 0, 0]])